name: Cloudflare
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: 'npm install'
      - name: deploy
        run: 'npm run deploy'
        env:
          CF_API_TOKEN: ${{secrets.CF_API_TOKEN}}
